### ISSUE TITLE
Need GPLv3+ compatible license.

### ISSUE THREAD

**Issue by milkypostman** [mandoku/mandoku-tls#1]
This package is being removed from MELPA due to incompatible license.

To be re-added to MELPA this package must have a [license compatible with GPLv3 and later](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).

**Comment by cwittern** [comment]
Added the line
;; License: GPL v3, or any later version
to the lisp file to clarify the license.
Please re-add to MELPA
